### PR TITLE
Update to v1.24 (build 4), using SDL v2.0.12, DarkEdif v6

### PR DESCRIPTION
**Pull request by SortaCore**
Switched to DarkEdif.
Minified static SDL library, follow guide in README to see changes. SDL is included in repository.
Uses static VS runtime - no more dependency on Visual Studio redistributable, or external SDL2.dll file.
Runtime MFX is now 945kb, instead of 19kb + 1.2mb DLL + redist.
However, the redist dependency can be re-enabled by changing the INI file and rebuilding.

Uses REFLAG::NONE instead of DISPLAY, which would pointlessly call DisplayRunObject().
Fixed error checks in initializing SDL function, which would treat SDL_GetError() as returning number, when it returned text.
Added more error checks and logging to SDL initialization.
Added action for importing a game controller mapping file.
Added Fusion debugger item showing number of joysticks.
Edited help file for new action.
DarkEdif auto-update notification enabled.

### CODE REVIEW

**Comment by PiKeyAr** [comment]
Considering the amount of change I think it would be better to keep it a separate fork, perhaps even with a different extension ID and filename.

**Comment by SortaCore** [comment]
The Action/Condition/Expression IDs match up, so it is a drop-in replacement MFX for the MMF2SDK variant (the original).
If we have two forks/repos, we double the maintenance, potentially make one obsolete by not updating it enough, and it's easy to keep them confused with version numbers. It doesn't seem practical to do that.

I'm open to becoming a collaborator on your repo after it's merged, though. DarkEdif is easy to get the hang of and despite the seemingly huge change, the main code for the functions is for the most part a copy-paste. Compare the Handle ticking, [MMF2SDK](https://github.com/PiKeyAr/SDLJoystick/blob/master/Runtime.cpp#L215) versus [DarkEdif](https://github.com/SortaCore/SDLJoystick-1/blob/master/DarkEdif/SDLJoy/Extension.cpp#L258).

**Comment by SortaCore** [comment]
Hey @PiKeyAr, did you miss my reply?

**Comment by PiKeyAr** [comment]
I'm still not sure how to deal with this, but I don't feel comfortable merging it. Here are the main reasons I don't want to merge it:

- The configurations other than Runtime and Runtime Unicode don't compile in Visual Studio, producing a number of errors in `darkedif.cpp`. The same happens with the DarkEdif template btw. I'm probably doing something wrong but there are no clear instructions on how to build this.
image

- SDL update instructions. Nobody should have to go through all those steps just to update SDL. I'd imagine there could be an easier way that also doesn't impose archaic restrictions such as no spaces in file paths.

- After looking at the whole thing again, I can't say I'm generally in favor of switching the SDK. Since it's already done, I'd insist on my original suggestion to keep your own version of the extension. I don't have the energy to adjust to the new SDK just to be able to maintain it. At the same time I don't feel comfortable letting you take over because I want to keep the original version and I might need to change something in the future. I don't think there's going to be a lot of confusion if there are two versions of it, and having to maintain a separate version for my own purposes isn't much of a problem.


I appreciate the effort, but sorry, I really don't think this is going to work out.

**Comment by SortaCore** [comment]
> * The configurations other than Runtime and Runtime Unicode don't compile in Visual Studio, producing a number of errors in `darkedif.cpp`. The same happens with the DarkEdif template btw. I'm probably doing something wrong but there are no clear instructions on how to build this.
>   image
I've tested it here with no issues, but I'll be happy to work with you to fix anything that's off.
The instructions are in the MMF2Exts repository's README, home of DarkEdif, but there's no extra steps. You just need Visual Studio 2017 or higher, so you can use C++17 features.

> * SDL update instructions. Nobody should have to go through all those steps just to update SDL. I'd imagine there could be an easier way that also doesn't impose archaic restrictions such as no spaces in file paths.
That's a restriction inherited from CMake, what SDL uses, not some strange way I'm using SDL. FFmpeg and other libraries using CMake are even more convoluted.  
There is a couple of file edits that are part of making it static, and compatible with VS, but unfortunately that's as simple as SDL custom compiling will get. Your complaint here should be directed at SDL maintainers.  
You can use the pre-built SDL statics, but that makes an unnecessarily large extension, as they'll include all the unused SDL functionality, like rendering, OpenGL stuff, threading code, etc... particularly if you're building dynamic and the compiler can't pull only the necessary functions from a static lib file.  
The instructions create the smallest SDL possible. Don't get caught up in the number of steps, it's fairly easy to follow.

> I don't think there's going to be a lot of confusion if there are two versions of it, and having to maintain a separate version for my own purposes isn't much of a problem.
As someone who develops Lacewing Blue, which runs alongside the Relay version, I can say from experience, there is unnecessary confusion; and in addition to that, one ended up being developed where the other was not. You'll get bug reports submitted for my version to you, and vice versa.  
I can't really afford to maintain another project, but I will do so.

Since the DarkEdif SDK will be made compatible with Android, and probably iOS later, so using the same codebase you can build for multiple platforms, you should be getting familiar with it.

However, if despite my advice and experience you still want to do it the way you are familiar with... there is a bug in the CreateRunObject function's error checking, and your extension's A/C/E has ranges of numbers which are not bound-checked, resulting in a crash if misused, which is going to confuse any end user. You may also want to convert to Unicode compatibility to prevent unnecessary character conversions in CF2.5 runtime. (All that's done already in my version.)

**Comment by SortaCore** [comment]
Due to your code change, this pull request now has conflicts and is invalid, and you appear to have abandoned it, so I'm closing it. Please learn how to keep an open line of communication in future when collaborating with other people.

**Pull request closed without merging**
